[package]
name = "mini-browser-v2"
version = "0.2.1"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "1"
tauri = { version = "2", features = ["tray-icon"] }

[build-dependencies]
tauri-build = { version = "2" }
